### ISSUE TITLE
* 

### ISSUE THREAD

**Issue by Stefan-Espant** [amirdev98/the-startup-responsive-interactieve-website#2]
Zet boven aan in je `css` de volgende property om je pagina te resetten.

```css
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}
```
